添加Steam库模板
mirai-mamori/Sakurairo pull request #1038
Opened 2024-12-31 12:46 UTC by Ummio

2025-01-11 11:32 UTC, mirai-mamori commented
@bymoye 来看看有没有要优化的

2025-01-24 17:22 UTC, bymoye commented
这个head这样写真的可以吗

2025-01-24 17:24 UTC, bymoye requested changes
请参考其余模板，使用REST API形式。

2025-02-12 07:48 UTC, KotoriK commented
> 请参考其余模板，使用REST API形式。

相关REST API开放出来是为了什么别的用途嘛

2025-02-12 07:56 UTC, KotoriK commented on user/page-steam.php
> +        display: none;
尽可能不依赖css样式来禁用评论区，可以看看有没有相应的WP函数，或者WP内置的功能（好像页面默认是没有评论区的

2025-02-12 07:56 UTC, KotoriK commented on user/page-steam.php
> +    .row {
过于简单的css规则可能会和别的地方冲突

2025-02-14 03:01 UTC, bymoye commented
> > 请参考其余模板，使用REST API形式。
> 
> 相关REST API开放出来是为了什么别的用途嘛

一致性

2025-02-23 08:33 UTC, merged