修复“登录后跳转”功能不生效的问题
mirai-mamori/Sakurairo pull request #643
Opened 2022-12-19 06:17 UTC by Molyleaf

2022-12-19 06:24 UTC, KotoriK requested changes
改个路径而已，没必要把模板拷两次

2022-12-19 06:24 UTC, KotoriK commented
记得写主题选项

2022-12-19 06:26 UTC, Molyleaf commented
主题选项使用的就是原来的“登录后跳转”选项

2022-12-19 06:28 UTC, KotoriK commented
> 主题选项使用的就是原来的“登录后跳转”选项

那估计描述要改一下，那个是给登录模板用的选项
@mirai-mamori

2022-12-19 06:37 UTC, Molyleaf commented
现在开启“登录后跳转”，登录后直接跳转到后台，关闭时跳转到登录前页面

2022-12-26 01:25 UTC, KotoriK requested changes
确认了一下```exlogin_url```的描述：
https://github.com/mirai-mamori/Sakurairo/blob/f3083d91240dded03ee387e8d4166178cd35d316/opt/options/theme-options.php#L3466-L3472
感觉```login_urlskip```控制```wp_login_url()```的传参就好了，不要导致```login_urlskip```打开时覆盖```exlogin_url```的行为

2023-02-27 07:42 UTC, KotoriK approved these changes

2023-02-27 07:42 UTC, merged